version: '3'
services:
  nexus:
    restart: always
    image: sonatype/nexus3
    ports: 
      - 8010:8081
    privileged: true
    volumes:
      - /data/docker_data/nexus_data:/nexus-data
  mysql:
    restart: always
    image: mysql:5.7.22
    container_name: mysql
    privileged: true
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --max_connections=1000
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
      --group_concat_max_len=102400 
      --default-time_zone='+8:00'
    volumes:
      - /data/docker_data/mysql_data:/var/lib/mysql
  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq
    privileged: true
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - /data/docker_data/rabbitmq_data:/var/lib/rabbitmq